### ISSUE TITLE
발걸음 소리가 나지 않습니다

### ISSUE THREAD

**Issue by Sweetnut1018** [Static-Devs/Nutscript-FA-Ver#8]
기존 넛스크립트 1.0 버그인데 혹시 고치실 수 있을까 하구요.
따로 지정한 뛰는 발걸음 소리는 들리는데, 그냥 발걸음 소리가 들리질 않네요.
기껏해야 금속 재질 위에서 점프할 때나 들림

**Comment by chino1120** [comment]
잘 들리는데..?

**Comment by 10sa** [comment]
시네마에서 설정해야 할탠대요?

**Comment by chino1120** [comment]
핲라 스체마 쓰는데 발소리 잘 들림

**Comment by 10sa** [comment]
close
